<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
        <HintPath>..\..\..\.dotnet\shared\Microsoft.AspNetCore.App\10.0.10\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.Extensions.Hosting.Abstractions">
        <HintPath>..\..\..\.dotnet\shared\Microsoft.AspNetCore.App\10.0.10\Microsoft.Extensions.Hosting.Abstractions.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.Extensions.Logging.Abstractions">
        <HintPath>..\..\..\.dotnet\shared\Microsoft.AspNetCore.App\10.0.10\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BytexDigital.BattlEye.Rcon" Version="1.0.3-preview.1718920183" />
    </ItemGroup>

</Project>
