// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Migrations.Migrations
{
    [DbContext(typeof(ConfigDbContext))]
    [Migration("20260824145149_AddSeparateInstanceModTables")]
    partial class AddSeparateInstanceModTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Domain.Manager.CustomMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Instanceid")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTimeOfDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("WaitTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Instanceid");

                    b.ToTable("MESSAGES");
                });

            modelBuilder.Entity("Domain.Manager.Instance", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RConPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RConPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("adminLog")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("autoStartServer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("backupPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("cpuCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("deleteBackups")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("doLogs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("freezeCheck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("hostName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("instanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("limitFPS")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("makeBackups")
                        .HasColumnType("INTEGER");

                    b.Property<string>("mapName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("maxKeepTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("missionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("missionTemplateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("netLog")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("noFilePatching")
                        .HasColumnType("INTEGER");

                    b.Property<string>("profileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("restartInterval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("restartOnUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("serverConfigName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("serverFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("serverPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("steamPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("steamQueryPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("vanillaMissionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("INSTANCES");
                });

            modelBuilder.Entity("Domain.Manager.InstanceClientMod", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModId")
                        .HasColumnType("TEXT");

                    b.HasKey("InstanceId", "ModId");

                    b.HasIndex("ModId");

                    b.ToTable("INSTANCE_CLIENT_MODS", (string)null);
                });

            modelBuilder.Entity("Domain.Manager.InstanceServerMod", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModId")
                        .HasColumnType("TEXT");

                    b.HasKey("InstanceId", "ModId");

                    b.HasIndex("ModId");

                    b.ToTable("INSTANCE_SERVER_MODS", (string)null);
                });

            modelBuilder.Entity("Domain.Manager.Mod", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("workshopID")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("MODS");
                });

            modelBuilder.Entity("Domain.Manager.SteamCredentials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SteamPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("STEAM_CREDENTIALS");
                });

            modelBuilder.Entity("Domain.Scheduler.Ban", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RemainingTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BANS");
                });

            modelBuilder.Entity("Domain.Scheduler.Player", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("PLAYERS");
                });

            modelBuilder.Entity("Domain.Scheduler.SchedulerConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("BadNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilteredNickMsg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Timeout")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseNickFilter")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SCHEDULER_CONFIGS");
                });

            modelBuilder.Entity("Domain.Scheduler.ServerPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BanId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWhitelisted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BanId")
                        .IsUnique();

                    b.HasIndex("InstanceId");

                    b.HasIndex("PlayerId");

                    b.ToTable("SERVER_PLAYERS");
                });

            modelBuilder.Entity("Domain.Manager.CustomMessage", b =>
                {
                    b.HasOne("Domain.Manager.Instance", null)
                        .WithMany("customMessages")
                        .HasForeignKey("Instanceid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Manager.InstanceClientMod", b =>
                {
                    b.HasOne("Domain.Manager.Instance", "Instance")
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Manager.Mod", "Mod")
                        .WithMany()
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");

                    b.Navigation("Mod");
                });

            modelBuilder.Entity("Domain.Manager.InstanceServerMod", b =>
                {
                    b.HasOne("Domain.Manager.Instance", "Instance")
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Manager.Mod", "Mod")
                        .WithMany()
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");

                    b.Navigation("Mod");
                });

            modelBuilder.Entity("Domain.Scheduler.ServerPlayer", b =>
                {
                    b.HasOne("Domain.Scheduler.Ban", "Ban")
                        .WithOne()
                        .HasForeignKey("Domain.Scheduler.ServerPlayer", "BanId");

                    b.HasOne("Domain.Manager.Instance", "Instance")
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Scheduler.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("Instance");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Domain.Manager.Instance", b =>
                {
                    b.Navigation("customMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
