// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Migrations.Migrations
{
    [DbContext(typeof(ConfigDbContext))]
    [Migration("20260903184925_AddPositionToCustomMessage")]
    partial class AddPositionToCustomMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Domain.Manager.Instance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RConPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RConPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("adminLog")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("autoStartServer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("backupPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("cpuCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("deleteBackups")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("doLogs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("freezeCheck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("hostName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("limitFPS")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("makeBackups")
                        .HasColumnType("INTEGER");

                    b.Property<string>("mapName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("maxKeepTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("missionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("missionTemplateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("netLog")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("noFilePatching")
                        .HasColumnType("INTEGER");

                    b.Property<string>("profileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("serverConfigName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("serverFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("serverPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("steamPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("steamQueryPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("vanillaMissionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("INSTANCES");
                });

            modelBuilder.Entity("Domain.Manager.InstanceClientMod", b =>
                {
                    b.Property<int>("InstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("InstanceId", "ModId");

                    b.HasIndex("ModId");

                    b.ToTable("INSTANCE_CLIENT_MODS");
                });

            modelBuilder.Entity("Domain.Manager.InstanceServerMod", b =>
                {
                    b.Property<int>("InstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("InstanceId", "ModId");

                    b.HasIndex("ModId");

                    b.ToTable("INSTANCE_SERVER_MODS");
                });

            modelBuilder.Entity("Domain.Manager.Mod", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("workshopID")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("MODS");
                });

            modelBuilder.Entity("Domain.Manager.SteamCredentials", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("STEAM_CREDENTIALS");
                });

            modelBuilder.Entity("Domain.Scheduler.CustomMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTimeOfDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchedulerConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("WaitTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SchedulerConfigId");

                    b.ToTable("MESSAGES");
                });

            modelBuilder.Entity("Domain.Scheduler.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ROLES");
                });

            modelBuilder.Entity("Domain.Scheduler.SchedulerConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("BadNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilteredNickMsg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Timeout")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseNickFilter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("restartInterval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("restartOnUpdate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SCHEDULER_CONFIGS");
                });

            modelBuilder.Entity("Domain.Scheduler.ServerPlayer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWhitelisted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RoleId");

                    b.ToTable("SERVER_PLAYERS");
                });

            modelBuilder.Entity("Domain.Scheduler.User", b =>
                {
                    b.Property<string>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("PLAYERS");
                });

            modelBuilder.Entity("Domain.Manager.InstanceClientMod", b =>
                {
                    b.HasOne("Domain.Manager.Instance", null)
                        .WithMany("clientMods")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Manager.Mod", "Mod")
                        .WithMany()
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mod");
                });

            modelBuilder.Entity("Domain.Manager.InstanceServerMod", b =>
                {
                    b.HasOne("Domain.Manager.Instance", null)
                        .WithMany("serverMods")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Manager.Mod", "Mod")
                        .WithMany()
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mod");
                });

            modelBuilder.Entity("Domain.Scheduler.CustomMessage", b =>
                {
                    b.HasOne("Domain.Scheduler.SchedulerConfig", null)
                        .WithMany("customMessages")
                        .HasForeignKey("SchedulerConfigId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Scheduler.ServerPlayer", b =>
                {
                    b.HasOne("Domain.Manager.Instance", "Instance")
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Scheduler.User", "User")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Scheduler.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Manager.Instance", b =>
                {
                    b.Navigation("clientMods");

                    b.Navigation("serverMods");
                });

            modelBuilder.Entity("Domain.Scheduler.SchedulerConfig", b =>
                {
                    b.Navigation("customMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
