<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="BytexDigital.BattlEye.Rcon">
        <HintPath>..\..\..\.nuget\packages\bytexdigital.battleye.rcon\1.0.3-preview.1718920183\lib\netstandard2.0\BytexDigital.BattlEye.Rcon.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
        <HintPath>..\..\..\.dotnet\shared\Microsoft.AspNetCore.App\10.0.10\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.Extensions.Logging.Abstractions">
        <HintPath>..\..\..\.dotnet\shared\Microsoft.AspNetCore.App\10.0.10\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BytexDigital.BattlEye.Rcon" Version="1.0.3-preview.1718920183" />
      <PackageReference Include="LibGit2Sharp" Version="0.32.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
    </ItemGroup>

</Project>
